### ISSUE TITLE
pip install tre

### ISSUE THREAD

**Issue by tandermann** [laurikari/tre#72] opened 2019-08-15 11:59 UTC
I would like to use tre in python3 but the `pip install tree` fails. Is there any way to fix that and make it available for python3?

**Comment by mcepl** [comment] 2020-03-03 22:10
Isn’t this a duplicate of #22?

**Comment by dag-erling** [comment] 2024-07-24 20:00
Try `pip install tre` instead.

**Closed by dag-erling** 2024-07-24 20:00 UTC
