### ISSUE TITLE
Build Warnings

### ISSUE THREAD

**Issue by djeraseit** [laurikari/tre#73] opened 2020-02-25 00:33 UTC
configure.ac:516: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:516: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:516: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.

**Comment by rathann** [comment] 2021-12-13 11:16
Duplicate of #66 .

**Closed** 2024-07-25 22:56 UTC
