### ISSUE TITLE
Found a simple expression that fails on OSX, in the latest TRE, but passes in ICU on OSX

### ISSUE THREAD

**Issue by dhoerl** [laurikari/tre#9] opened 2013-07-03 23:19 UTC
This expression succeeds when it should fail:

```
ret = tre_regcomp(&trx, "^(?:(?:(?:(?:(?:[0-9]){1,4}):){0,4})(?:(?:[0-9]){1,4}))?::$", REG_EXTENDED | REG_NOSUB);
test = "1:2:3:4:5:6::";
ret = tre_regexec(&trx, test, 0, NULL, 0);
```

**Comment by dag-erling** [comment] 2024-07-25 16:22
If you run this with debugging enabled (`./configure --enable-debug`) you will see that after AST expansion, there are two literal nodes with position 17, two with position 18, and two with position 19. Node positions are supposed to be unique. During AST expansion, new nodes may be created with the same positions as existing nodes, and when that happens the existing nodes are supposed to be renumbered, but this does not always happen as intended. I believe #105 fixes this. #

**Comment by dag-erling** [comment] 2024-07-25 23:45
The PR hasn't been merged yet.

**Closed** 2024-07-30 12:08 UTC
Labels: bug
