### ISSUE TITLE
Word character matching not working

### ISSUE THREAD

**Issue by wkirkboyd** [laurikari/tre#71] opened 2019-04-19 03:02 UTC
This is the same setup as issue #70 with test.txt containing only "Dab".
But this problem seems to apply to any platform.

This expression does not match my test string:
`agrep "^[\w]a" test.txt`

However the equivalents do match:
`agrep "^[A-Z]a" test.txt`
`agrep "^[[:alnum:]]a`

**Comment by dag-erling** [comment] 2024-07-30 16:51
Duplicate of #20

**Closed by dag-erling** 2024-07-30 16:51 UTC
